spring:
  datasource:
    url: jdbc:mysql://localhost:3307/pr_reviewer?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: app
    password: app1234

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true


logging:
  level:
    com.coderev: DEBUG
    org.springframework.security: DEBUG
